#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys

#import from the 21 Developer Library
from two1.commands.config import Config
from two1.lib.wallet import Wallet
from two1.lib.bitrequests import BitTransferRequests
import requests
import pyperclip

#set up bitrequest client for BitTransfer requests
try:
	wallet = Wallet()
except Exception:
	print('Something went wrong -- check your network connection')
	sys.exit(-1)

username = Config().username
requests = BitTransferRequests(wallet, username)

# Temporary for debug purposes -- replace w/ actual server url when no longer running server / client on same machine
BASE_URL = "http://0.0.0.0:5000" 

def cli():
	try:
		file = open(sys.argv[1], 'rb')
	except Exception:
		print("No such file exists: '" + sys.argv[1] + "'")
		sys.exit(-1)

	files = {'file': file}
	
	try:
		r = requests.post(BASE_URL + '/upload', files=files)
	except Exception:
		print("Couldn't connect to server -- check your network connection.")
		sys.exit(-1)

	if r.status_code == 200:	
		pyperclip.copy(BASE_URL + r.text)
		print("Link has been copied to your clipboard!")
	else:
		print("Server encountered an error.")

if __name__ == '__main__':
	if len(sys.argv) < 2:
		print('Include filename you would like to upload.')
		print('Example:')
		print('./minishard21 /path/to/file')
	cli()